# Generated by Django 4.1.7 on 2024-02-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='cat',
            field=models.CharField(choices=[('National', 'National'), ('LGU', 'LGU')], default='green', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lgu',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='voting.lgu'),
        ),
        migrations.AddField(
            model_name='voter',
            name='lgu',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='voting.lgu'),
        ),
    ]
