# Generated by Django 4.1.7 on 2024-02-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_lgu_position_cat_candidate_lgu_voter_lgu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='lgu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.lgu'),
        ),
    ]
